# Generated by Django 5.2.9 on 2026-04-29 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_histories', to='accounts.childprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_histories', to='quiz.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_histories', to='quiz.choice')),
            ],
            options={
                'db_table': 'answer_histories',
                'indexes': [models.Index(fields=['child', 'question', 'answered_at'], name='answer_hist_child_i_f37607_idx')],
            },
        ),
    ]
